name: http_sandbox_viewer
description: "A Flutter package for debugging HTTP requests and responses with Swagger-like API definitions for Retrofit + Dio."
version: 0.1.0
homepage: https://github.com/Pregum/http_sandbox_viewer
repository: https://github.com/Pregum/http_sandbox_viewer
issue_tracker: https://github.com/Pregum/http_sandbox_viewer/issues

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
